### ISSUE TITLE
放一张图片保持不动该怎么展示?

### ISSUE THREAD

**Issue by LotusWallet** [TonyChenn/CustomAndroidCamera#1]
保持你现在运行的效果，贴一张图片上去，展示在屏幕最中央，但是转动手机的时候，图片不允许跟着手机一起转动，这个效果该怎么实现呢

**Comment by LotusWallet** [comment]
AR效果

**Comment by TonyChenn** [comment]
> 保持你现在运行的效果，贴一张图片上去，展示在屏幕最中央，但是转动手机的时候，图片不允许跟着手机一起转动，这个效果该怎么实现呢

调用设备的陀螺仪，获得旋转角度相关信息，再对图片进行旋转即可。
